# Generated by Django 2.0.4 on 2018-05-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('number', models.IntegerField(unique=True, verbose_name='Нумар')),
                ('certificate', models.FileField(blank=True, default='', null=True, unique=True, upload_to='certificates/%Y/%m/%d/', verbose_name='Файл пасведчання')),
                ('baptized_name', models.CharField(max_length=30, verbose_name='Імя ахрышчанага')),
                ('baptized_middle_name', models.CharField(max_length=30, null=True, verbose_name='Імя па бацьку ахрышчанага')),
                ('baptized_surname', models.CharField(max_length=30, verbose_name='Прозвішча ахрышчанага')),
                ('godfather', models.CharField(max_length=100, null=True, verbose_name='Хросны бацька')),
                ('godmother', models.CharField(max_length=100, null=True, verbose_name='Хросная маці')),
                ('saint_name', models.CharField(max_length=300, null=True, verbose_name='Імя святога')),
                ('saint_date', models.DateField(null=True, verbose_name='Дзень Анёла')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dignity', models.CharField(choices=[('IE', 'іярэй'), ('PR', 'протаярэй')], default='IE', max_length=2, verbose_name='Сан')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Імя святара')),
            ],
            options={
                'verbose_name': 'Святар',
                'verbose_name_plural': 'Святары',
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('number', models.IntegerField(unique=True, verbose_name='Нумар')),
                ('certificate', models.FileField(blank=True, default='', null=True, unique=True, upload_to='certificates/%Y/%m/%d/', verbose_name='Файл пасведчання')),
                ('fiance_name', models.CharField(max_length=30, verbose_name='Імя жаніха')),
                ('fiance_middle_name', models.CharField(max_length=30, null=True, verbose_name='Імя па бацьку жаніха')),
                ('fiance_surname', models.CharField(max_length=30, verbose_name='Прозвішча жаніха')),
                ('fiancee_name', models.CharField(max_length=30, verbose_name='Імя нявесты')),
                ('fiancee_middle_name', models.CharField(max_length=30, null=True, verbose_name='Імя па бацьку нявесты')),
                ('fiancee_surname', models.CharField(max_length=30, verbose_name='Прозвішча нявесты')),
                ('witness1', models.CharField(max_length=100, null=True, verbose_name='Сведка №1')),
                ('witness2', models.CharField(max_length=100, null=True, verbose_name='Сведка №2')),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certs.Clergy', verbose_name='Святар')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baptism',
            name='priest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certs.Clergy', verbose_name='Святар'),
        ),
    ]
