# Generated by Django 2.0.4 on 2018-05-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clergy',
            unique_together={('dignity', 'name')},
        ),
    ]
