# Generated by Django 2.0.4 on 2018-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_auto_20180517_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baptism',
            options={'verbose_name': 'Хрышчэнне', 'verbose_name_plural': 'Хрышчэнні'},
        ),
        migrations.AlterModelOptions(
            name='wedding',
            options={'verbose_name': 'Вянчанне', 'verbose_name_plural': 'Вянчанні'},
        ),
        migrations.AlterField(
            model_name='baptism',
            name='baptized_middle_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Імя па бацьку ахрышчанага'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='fiance_middle_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Імя па бацьку жаніха'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='fiancee_middle_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Імя па бацьку нявесты'),
        ),
        migrations.AlterUniqueTogether(
            name='baptism',
            unique_together={('baptized_name', 'baptized_middle_name', 'baptized_surname')},
        ),
        migrations.AlterUniqueTogether(
            name='wedding',
            unique_together={('fiance_name', 'fiance_middle_name', 'fiance_surname', 'fiancee_name', 'fiancee_middle_name', 'fiancee_surname')},
        ),
    ]
