# Generated by Django 2.0.4 on 2018-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0003_auto_20180517_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baptism',
            options={'ordering': ['-date'], 'verbose_name': 'Хрышчэнне', 'verbose_name_plural': 'Хрышчэнні'},
        ),
        migrations.AlterField(
            model_name='baptism',
            name='certificate',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='certificates/%Y/%m/%d/', verbose_name='Файл пасведчання'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='godfather',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Хросны бацька'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='godmother',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Хросная маці'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='saint_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дзень Анёла'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='saint_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Імя святога'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='certificate',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='certificates/%Y/%m/%d/', verbose_name='Файл пасведчання'),
        ),
    ]
