# Generated by Django 2.0.4 on 2018-05-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0004_auto_20180517_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={'ordering': ['-date'], 'verbose_name': 'Вянчанне', 'verbose_name_plural': 'Вянчанні'},
        ),
    ]
